// formix-admin/src/app/pages/ingredients/ingredients.component.ts
import { Component, inject, signal, computed } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DataService } from '../../core/data.service';
import { ToastService } from '../../shared/toast.service';
import { DrawerComponent } from '../../shared/drawer/drawer.component';
import { IconComponent } from '../../shared/icon/icon.component';

@Component({
  selector: 'app-ingredients',
  standalone: true,
  imports: [FormsModule, DrawerComponent, IconComponent],
  template: `
    <div class="page">
      <div class="page__header">
        <div>
          <div class="page__title">Ingredients</div>
          <div class="page__desc">Master data. Allergens flow through to labels, QA checks and sequencing rules.</div>
        </div>
        <div class="page__actions">
          <button class="btn btn--secondary"><app-icon name="upload" [size]="16"/>Import CSV</button>
          <button class="btn btn--primary" (click)="toast.push('New ingredient created')"><app-icon name="plus" [size]="16"/>New ingredient</button>
        </div>
      </div>

      <div class="filter-bar">
        <div class="input-group" style="flex:0 1 360px">
          <app-icon name="search" [size]="16"/>
          <input class="input" placeholder="Search ingredients…" [(ngModel)]="query"/>
        </div>
        <select class="select" style="width:200px" [(ngModel)]="allergenFilter">
          <option value="all">Any allergen status</option>
          <option value="any">Contains allergens</option>
          <option value="none">No allergens</option>
          <optgroup label="Specific allergen">
            @for (a of data.allergens; track a.id) {
              <option [value]="a.id">{{ a.name }}</option>
            }
          </optgroup>
        </select>
        <div style="margin-left:auto;font-size:13px;color:var(--hs-fg-3)">{{ filtered().length }} of {{ data.ingredients.length }}</div>
      </div>

      <div class="card" style="overflow:hidden">
        <table class="tbl">
          <thead><tr>
            <th style="width:100px">Code</th>
            <th>Name</th>
            <th style="width:160px">Supplier</th>
            <th>Allergens</th>
            <th class="num" style="width:80px">Unit</th>
            <th class="num" style="width:100px">Cost</th>
            <th class="num" style="width:100px">Stock</th>
            <th class="num" style="width:90px">Use-by</th>
          </tr></thead>
          <tbody>
            @for (i of filtered(); track i.code) {
              <tr (click)="selected.set(i.code)">
                <td class="mono" style="font-weight:600">{{ i.code }}</td>
                <td style="font-weight:600">{{ i.name }}</td>
                <td class="muted">{{ i.supplier }}</td>
                <td>
                  @if (i.allergens.length) {
                    @for (id of i.allergens; track id) {
                      <span class="chip chip--allergen" style="margin-right:3px;font-size:10px;padding:2px 7px">{{ data.allergenName(id) }}</span>
                    }
                  } @else {
                    <span style="color:var(--hs-fg-muted);font-size:12px">none</span>
                  }
                </td>
                <td class="num mono">{{ i.unit }}</td>
                <td class="num mono">£{{ data.fmt(i.cost, 2) }}</td>
                <td class="num mono">{{ data.fmt0(i.stock) }}</td>
                <td class="num mono muted">{{ i.useBy ? i.useBy + ' d' : '—' }}</td>
              </tr>
            }
          </tbody>
        </table>
      </div>

      <!-- Ingredient editor drawer -->
      <app-drawer [open]="!!selected()" [title]="drawerTitle()" [hasFooter]="true" (close)="selected.set(null)">
        @if (selectedIng()) {
          <div style="display:flex;flex-direction:column;gap:16px">
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">
              <div class="field">
                <label class="field__label">Code</label>
                <input class="input mono" [value]="selectedIng()!.code" readonly/>
              </div>
              <div class="field">
                <label class="field__label">Unit of measure</label>
                <select class="select" [value]="selectedIng()!.unit">
                  <option>kg</option><option>L</option><option>g</option><option>ml</option><option>units</option>
                </select>
              </div>
            </div>
            <div class="field">
              <label class="field__label">Name</label>
              <input class="input" [value]="selectedIng()!.name"/>
            </div>
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">
              <div class="field">
                <label class="field__label">Supplier</label>
                <input class="input" [value]="selectedIng()!.supplier"/>
              </div>
              <div class="field">
                <label class="field__label">Cost per {{ selectedIng()!.unit }}</label>
                <input class="input mono" [value]="selectedIng()!.cost"/>
              </div>
            </div>
            <div class="field">
              <label class="field__label">Use-by specification (days from receipt)</label>
              <input class="input mono" [value]="selectedIng()!.useBy ?? ''"/>
              <div class="field__hint">Used during weighing to validate source barcode dates.</div>
            </div>
            <div>
              <div class="field__label" style="margin-bottom:10px">Allergens</div>
              <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">
                @for (a of data.allergens; track a.id) {
                  @let checked = selectedIng()!.allergens.includes(a.id);
                  <label [style]="allergenLabelStyle(checked)">
                    <input type="checkbox" [checked]="checked" style="accent-color:var(--hs-warning)"/>
                    {{ a.name }}
                  </label>
                }
              </div>
              <div style="font-size:12px;color:var(--hs-fg-3);margin-top:8px">
                <app-icon name="alert" [size]="12" style="vertical-align:-1px;color:var(--hs-warning)"/>
                Allergen words will appear in <b>BOLD UPPERCASE</b> on labels — legally required (Food Information Regs 2014).
              </div>
            </div>
          </div>
        }
        <ng-container slot="footer">
          <button class="btn btn--danger"><app-icon name="trash" [size]="16"/>Archive</button>
          <button class="btn btn--primary" (click)="save()"><app-icon name="check" [size]="16"/>Save</button>
        </ng-container>
      </app-drawer>
    </div>
  `,
})
export class IngredientsComponent {
  data = inject(DataService);
  toast = inject(ToastService);

  query = '';
  allergenFilter = 'all';
  selected = signal<string | null>(null);

  filtered = computed(() => this.data.ingredients.filter(i => {
    const q = this.query.toLowerCase();
    if (q && !i.name.toLowerCase().includes(q) && !i.code.toLowerCase().includes(q)) return false;
    if (this.allergenFilter === 'any' && i.allergens.length === 0) return false;
    if (this.allergenFilter === 'none' && i.allergens.length > 0) return false;
    if (this.allergenFilter !== 'all' && this.allergenFilter !== 'any' && this.allergenFilter !== 'none' && !i.allergens.includes(this.allergenFilter)) return false;
    return true;
  }));

  selectedIng = computed(() => this.selected() ? this.data.ingredient(this.selected()!) : undefined);
  drawerTitle = computed(() => this.selected() ? `${this.selected()} · ${this.selectedIng()?.name ?? ''}` : '');

  allergenLabelStyle(checked: boolean): string {
    return `display:flex;align-items:center;gap:8px;padding:8px 10px;border:1px solid ${checked ? 'var(--hs-warning)' : 'var(--hs-border)'};background:${checked ? 'var(--hs-warning-bg)' : 'white'};border-radius:8px;cursor:pointer;font-size:13px;font-weight:${checked ? 600 : 400}`;
  }

  save() { this.toast.push('Ingredient saved'); this.selected.set(null); }
}

// Formix - Web App/pages/Ingredients.jsx
/* global React, Icon, Chip, StatusChip, Button, Drawer, Tabs, AllergenChips, useToast,
   INGREDIENTS, ING, ALLERGENS, PREP_AREAS, allergenName, fmt */

const { useState: useSI, useMemo: useMI } = React;

function IngredientsPage() {
  const [query, setQuery] = useSI('');
  const [allergenF, setAllergenF] = useSI('all');
  const [selected, setSelected] = useSI(null);

  const filtered = useMI(() => INGREDIENTS.filter(i => {
    if (query && !(i.name.toLowerCase().includes(query.toLowerCase()) || i.code.toLowerCase().includes(query.toLowerCase()))) return false;
    if (allergenF === 'any' && i.allergens.length === 0) return false;
    if (allergenF === 'none' && i.allergens.length > 0) return false;
    if (allergenF !== 'all' && allergenF !== 'any' && allergenF !== 'none' && !i.allergens.includes(allergenF)) return false;
    return true;
  }), [query, allergenF]);

  return (
    <div className="page">
      <div className="page__header">
        <div>
          <div className="page__title">Ingredients</div>
          <div className="page__desc">Master data. Allergens flow through to labels, QA checks and sequencing rules.</div>
        </div>
        <div className="page__actions">
          <Button icon="upload">Import CSV</Button>
          <Button variant="primary" icon="plus">New ingredient</Button>
        </div>
      </div>

      <div className="filter-bar">
        <div className="input-group" style={{flex:'0 1 360px'}}>
          <Icon name="search" size={16}/>
          <input className="input" placeholder="Search ingredients…" value={query} onChange={e => setQuery(e.target.value)}/>
        </div>
        <select className="select" value={allergenF} onChange={e => setAllergenF(e.target.value)} style={{width:200}}>
          <option value="all">Any allergen status</option>
          <option value="any">Contains allergens</option>
          <option value="none">No allergens</option>
          <optgroup label="Specific allergen">
            {ALLERGENS.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
          </optgroup>
        </select>
        <div style={{marginLeft:'auto',fontSize:13,color:'var(--hs-fg-3)'}}>{filtered.length} of {INGREDIENTS.length}</div>
      </div>

      <div className="card" style={{overflow:'hidden'}}>
        <table className="tbl">
          <thead><tr>
            <th style={{width:100}}>Code</th>
            <th>Name</th>
            <th style={{width:160}}>Supplier</th>
            <th>Allergens</th>
            <th className="num" style={{width:80}}>Unit</th>
            <th className="num" style={{width:100}}>Cost</th>
            <th className="num" style={{width:100}}>Stock</th>
            <th className="num" style={{width:90}}>Use-by</th>
          </tr></thead>
          <tbody>
            {filtered.map(i => (
              <tr key={i.code} onClick={() => setSelected(i.code)}>
                <td className="mono" style={{fontWeight:600}}>{i.code}</td>
                <td style={{fontWeight:600}}>{i.name}</td>
                <td className="muted">{i.supplier}</td>
                <td><AllergenChips ids={i.allergens} small/></td>
                <td className="num mono">{i.unit}</td>
                <td className="num mono">£{fmt(i.cost,2)}</td>
                <td className="num mono">{fmt(i.stock,0)}</td>
                <td className="num mono muted">{i.useBy ? `${i.useBy} d` : '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <Drawer open={!!selected} onClose={() => setSelected(null)} title={selected ? `${selected} · ${ING[selected].name}` : ''}
        footer={selected ? <><Button variant="danger" icon="trash">Archive</Button><Button variant="primary" icon="check">Save</Button></> : null}>
        {selected && <IngredientEditor code={selected}/>}
      </Drawer>
    </div>
  );
}

function IngredientEditor({ code }) {
  const ing = ING[code];
  return (
    <div style={{display:'flex',flexDirection:'column',gap:16}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>
        <div className="field"><label className="field__label">Code</label><input className="input mono" defaultValue={ing.code}/></div>
        <div className="field"><label className="field__label">Unit of measure</label>
          <select className="select" defaultValue={ing.unit}><option>kg</option><option>L</option><option>g</option><option>ml</option><option>units</option></select>
        </div>
      </div>
      <div className="field"><label className="field__label">Name</label><input className="input" defaultValue={ing.name}/></div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>
        <div className="field"><label className="field__label">Supplier</label><input className="input" defaultValue={ing.supplier}/></div>
        <div className="field"><label className="field__label">Cost per {ing.unit}</label>
          <input className="input mono" defaultValue={ing.cost}/>
        </div>
      </div>
      <div className="field"><label className="field__label">Use-by specification (days from receipt)</label>
        <input className="input mono" defaultValue={ing.useBy || ''}/>
        <div className="field__hint">Used during weighing to validate source barcode dates.</div>
      </div>
      <div>
        <div className="field__label" style={{marginBottom:10}}>Allergens</div>
        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}>
          {ALLERGENS.map(a => {
            const checked = ing.allergens.includes(a.id);
            return (
              <label key={a.id} style={{display:'flex',alignItems:'center',gap:8,padding:'8px 10px',border:`1px solid ${checked?'var(--hs-warning)':'var(--hs-border)'}`,background:checked?'var(--hs-warning-bg)':'white',borderRadius:8,cursor:'pointer',fontSize:13,fontWeight:checked?600:400}}>
                <input type="checkbox" defaultChecked={checked} style={{accentColor:'var(--hs-warning)'}}/>
                {a.name}
              </label>
            );
          })}
        </div>
        <div style={{fontSize:12,color:'var(--hs-fg-3)',marginTop:8}}>
          <Icon name="alert" size={12} style={{verticalAlign:'-1px',color:'var(--hs-warning)'}}/> {' '}
          Allergen words will appear in <b>BOLD UPPERCASE</b> on labels — legally required (Food Information Regs 2014).
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { IngredientsPage });
